name: agri_bot
description: Agricultural Assistant Robot Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  http: ^1.1.0
  syncfusion_flutter_charts: ^26.2.14
  syncfusion_flutter_gauges: ^26.2.14
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0
  shimmer: ^3.0.0
  card_swiper: ^3.0.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/